# Generated by Django 3.1.4 on 2021-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20201205_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='connection',
        ),
        migrations.AddField(
            model_name='node',
            name='connections',
            field=models.ManyToManyField(blank=True, null=True, related_name='_node_connections_+', to='graph.Node'),
        ),
    ]
